### PR TITLE
support stats using Block/BlockStat table

### PR DESCRIPTION
**Pull request by hackmod**
## WARNING
this is a experimental fix to serve statistics without external apis (http://drawpie.com/etc_hash_rate_api is currently broken)

**Please do not merge it, execpt for testing.**

- migrate `public/js/stats/*.js` javascripts into angular directives. (almost no change except external apis)
- fixed `getMinerStats()` using the `Block` table (instead of BlockStat table)
- support `getHashrates()` using the `BlockStat` table.
- ~~The bomb chart is not work correctly.~~ fixed.
  - See also https://github.com/ethereumproject/ECIPs/issues/4#issuecomment-248544527
----
## prepare & run

- `node tools/stats.js` : initialize `BlockStat` table to show the network hashrate chart
  - you can rescan after drop the BlockStat table like as following
  - `RESCAN=10000:1000000 node tools/stats.js` (`interval:steps`)
- `npm start`

## screenshot

image

image

image

### CODE REVIEW

**Comment by akx20000a** [comment]
Epic commit! Will update https://classic.chainkorea.kr when we merge this one 😄

**Comment by akx20000a** [comment]
@hackmod @pyskell Since Classic defuses the difficulty bomb on block 5900000, I think using the ECIP-1010 chart is useless for now & the future ( also the alt-chains ). Instead, we can change them to the gaslimit chart or block time chart ( if we have them on our database ).

**Comment by hackmod** [comment]
- support mobile layout
- show high rank first. hide low rank miners.

image

**Comment by akx20000a** [comment]
@hackmod show high rank miners first. hide low rank miners. - This part was pretty annoying until it solved now 😄

**Pull request merged**
