### PR TITLE
support uncles

### PR DESCRIPTION
**Pull request by hackmod**
support `/uncle/hash` or `/uncle/blocknumber/uncleindex`

### CODE REVIEW

**Comment by pyskell** [comment]
This doesn't seem to work correctly:
`/uncle/0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347` gives a 404

image

`/uncle/blocknumber/5` redirects to the home page

Do these changes require resyncing the Mongo DB or for certain flags to be used with the node? I imagine uncles would be pretty readily pruned so maybe that is what's causing the issue.

**Comment by hackmod** [comment]
thankyou for your test.

Ive checked this feature with geth-1.8.3 over the ESN network.
and now I have mult-geth + ETC block chain. now time to recheck!

**Comment by hackmod** [comment]
`/uncle/2469098/0` or `/uncle/2469098` (same as `/uncle/blocknumber/0`) works find for me.

image

at the mult-geth console.
~~~.js
> eth.getBlock(2469098)
{
  difficulty: 7239591018789,
  extraData: "0x6e616e6f706f6f6c2e6f7267",
  gasLimit: 3516271,
  gasUsed: 1380253,
  hash: "0x1b8243438440837a2707dc0382032aee7218db170b1d8bac8d03c417d1378cec",
  logsBloom: "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000000000000000000000404000000002000000000000000000000000000100000000000000000000000000004000000000800000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001000100000000000000000000000000000000000000000000400000000000000000001000000000000",
  miner: "0x9eab4b0fc468a7f5d46228bf5a76cb52370d068d",
  mixHash: "0x0425bcf79f1c2bd7ed35c6f3d033482e6130fcf53da56078a07ee4fb4bca5e53",
  nonce: "0xd3ac191801619c66",
  number: 2469098,
  parentHash: "0x4ca13de453db144a0ce3a77aafaa133ff9eb3ad91f0a2f7e0e96e8d75afb8889",
  receiptsRoot: "0xeed92273072df44eddec10a9dad9f7f6361e36a29938f4a395d32a8baf9eb560",
  sha3Uncles: "0xb476a99a6e0f15a198be0bc20caf4254904af6f96820085655a5ecd91fc59c73",
  size: 1597,
  stateRoot: "0x3810dd581fc69f2fc752bc30344d6e3fc21d11b13f189cd05ee88e1422a3e7c5",
  timestamp: 1476931880,
  totalDifficulty: 43915595109218332756,
  transactions: ["0x488b87258e8ac8eb73dc0269af07cd5f6b66fc61bba40e9a6eda4a68325af586", "0x094237d973d5aba9727b54b121835f4c9db74b4fdfdfdd8fb931aa4182dc7a3b", "0x1393fcef33ce3074cc443ff4b309cc0d20a370f277c43cd4bd372a231ac8c87e", "0x584a8cc0f10e328980200409561e77d9b94094aca1849d9fd036613e1d40e7da"],
  transactionsRoot: "0x415b47f7cf0912617807f202a180db02957b4bc56e9363fde0593b028cbfaa53",
  uncles: ["0xf832877a85b40e44206b3fd265170dc0bb0931ccbc895555858581e42ed9c766"]
}
~~~

also `eth.getUncle(2469098)` or `eth.getUncle(2469098,0)` works find at the multi-geth console.
~~~.js
> eth.getUncle(2469098)
{
  difficulty: 7250203050949,
  extraData: "0xd5830103088650617269747986312e31322e30826c69",
  gasLimit: 3502572,
  gasUsed: 21000,
  hash: "0xf832877a85b40e44206b3fd265170dc0bb0931ccbc895555858581e42ed9c766",
  logsBloom: "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  miner: "0x6e023dae690c638ca1a6510dceccc6b6ff22d2a5",
  mixHash: "0x5560fb5d00bef980187c649495563ecde91dcc6eed1207d60b0c87ae417cd80c",
  nonce: "0xb7c37db007d81aff",
  number: 2469096,
  parentHash: "0x3e599c2bef4cc7572919cfadbd97bf687c6ad3317696a96c981df9319b96e572",
  receiptsRoot: "0x8f6e78a2997b219d7d94d8eaee5558b114c25542f33ea3d70ff409abb5ce0fa0",
  sha3Uncles: "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
  size: 541,
  stateRoot: "0xa6ca0da89fef10c62d35b398d17683d95a19cb330f521da188895f9efc7da1b6",
  timestamp: 1476931826,
  totalDifficulty: 0,
  transactionsRoot: "0x8048d12d6da70f63a9934c65aa66dea6f650436ea8df48061d7997eaa5a2707e",
  uncles: []
}
~~~

and Ive confirmed that the `/uncle/0xf832877a85b40e44206b3fd265170dc0bb0931ccbc895555858581e42ed9c766` query didn't work.

**Comment by pyskell** [comment]
Hrmm, eth.getBlock() seems to be non-standard, referring to the Parity docs it looks like this is necessary: https://wiki.parity.io/JSONRPC-eth-module#eth_getunclebyblockhashandindex

Anyway can't get to this today but I'll better review this PR tomorrow.

**Comment by pyskell** [comment]
My apologies, the day has gotten away from me. Aiming to look this and the other PRs over tomorrow.

**Comment by pyskell** [comment]
Figured this out, web3 doesn't seem to have the functionality to use an uncle hash to `getUncle()`, it needs a block hash and an index. So `/uncle/hash` won't work, but `/uncle/blockhash/index` or `/uncle/blocknumber/index` will.

https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethgetuncle

**Comment by pyskell** [comment]
This was merged into dev.

**Pull request closed without merging**
