### PR TITLE
First update for ETC/Hashrate Chart

### PR DESCRIPTION
**Pull request by kimisan**
First update for ETC/Hashrate Chart

### CODE REVIEW

**Comment by elaineo** [comment]
Great! Is this a real data source? If so I'll link to it from the home page.

**Comment by kimisan** [comment]
I use @matthewjamesr 's api , https://api.minergate.com/1.0/etc/status, to record the data to my mongodb server hour to hour.

And I made a api server, http://drawpie.com/etc_hash_rate_api .

This data originally is coming from @matthewjamesr 's api.

**Comment by elaineo** [comment]
okay awesome! i'll give it a header and footer and link from the dropdown menus.

**Comment by kimisan** [comment]
Any new assignment of Visualizing Stats & Data , please let me know (^ω^)

**Comment by elaineo** [comment]
Miner distribution would be good: http://etherscan.io/stats/miner?range=7

If you let me know the JSON data format  you need, I can provide an API for the data.

**Comment by kimisan** [comment]
Wow, this chart is no problem.
I can accept any kind of JSON data format ,
but need  
1. miner name 
2. miner share percentage . 
3. Cors

**Comment by matthewjamesr** [comment]
@kimisan Glad that the API is working well for you :+1:

**Comment by kimisan** [comment]
@matthewjamesr Thanks for ETC API !

**Pull request merged**
