### PR TITLE
Optimize frontpage CSS

### PR DESCRIPTION
**Pull request by Empty2k12**
Optimied the frontpage CSS so it looks more clean and elements like scrollbars look similar to the theme.
Also updated README to show that this is indeed a ETC Explorer, not ETH

### CODE REVIEW

**Comment by matthewjamesr** [comment]
@Empty2k12 can you please move the loading indicator below your new table and center it. Will merge PR afterwards.

**Comment by Empty2k12** [comment]
@matthewjamesr which new table? I removed a obsoltete hardcoded style from the table :)

**Comment by matthewjamesr** [comment]
@Empty2k12 additional comment: can we add number of confirmations to the table after the **block** column?

**Comment by matthewjamesr** [comment]
@Empty2k12 ah ok :) would you be willing to do the placement and alignment changes to move the spinner below the transactions table?

**Comment by Empty2k12** [comment]
@matthewjamesr for me the sinner is only showing up when the table is not visible yet. Could you create a screenshot of the changes you want me to do? Thank you!

**Comment by matthewjamesr** [comment]
I took care of it :). Thanks for the great work!

**Comment by Empty2k12** [comment]
@matthewjamesr Happy to contribute! Depending on my internet situation in the following days I will try to add more things!

**Pull request merged**
